### ISSUE TITLE
1.16.5 forge 36.2.8 Particles fail to find description json

### ISSUE THREAD

**Issue by NighthowlerStudios** [Cheaterpaul/fallingleaves#10]
Caused by: java.lang.IllegalStateException: Failed to load description for particle fallingleaves:falling_leaf
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:226) ~[?:?]
	at net.minecraft.client.particle.ParticleManager.func_215238_b(ParticleManager.java:169) ~[?:?]
	at net.minecraft.client.particle.ParticleManager$$Lambda$3397/1080945842.run(Unknown Source) ~[?:?]

...

Caused by: java.io.FileNotFoundException: fallingleaves:particles/falling_leaf.json
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:63) ~[?:?]
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:205) ~[?:?]
	at net.minecraft.client.particle.ParticleManager.func_215238_b(ParticleManager.java:169) ~[?:?]
	at net.minecraft.client.particle.ParticleManager$$Lambda$3397/1080945842.run(Unknown Source) ~[?:?]

...

**Comment by SpencerMeow** [comment]
This is happening to me too.

**Comment by SzczurekYT** [comment]
Me too
