### ISSUE TITLE
Log spam from null direction [1.16.5]

### ISSUE THREAD

**Issue by Dunkmania101** [Cheaterpaul/fallingleaves#20]
Hi, I've been getting some really bad lag and I think it's because of some log spam about a null value.
The message was very unspecific about the source of the error, but it listed a line in this mod as an event listener that was called at some point around the exception which it said was from a null value being passed into a method related to the Direction class. Of all of the event listeners it provided, the line changed in commit d74ff92a14faec454d122c7556d2c08a8e0c8667 is the only one that seemed relevant. It's hard to tell if I'm right because of the vagueness of the log message, but this is my best guess.
I'm about to launch my game with the previous release of this mod to see if the issue goes away, I'll add a comment with my results.

Here's the log message:
```
[14:28:43] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 16035ms or 320 ticks behind
[14:28:45] [SoundControl Sound Processor/WARN]: SoundControl Sound Processor is lagging; behind 31 msecs
[14:28:46] [SoundControl Sound Processor/WARN]: SoundControl Sound Processor is lagging; behind 1417 msecs
[14:28:49] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.util.Direction.func_82601_c()" because "☃" is null
	Index: 42
	Listeners:
		0: HIGHEST
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@636bb439
		2: ASM: class ovh.corail.tombstone.event.EventHandler onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		3: ASM: class com.ma.events.InputDisabler onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		4: ASM: class me.desht.pneumaticcraft.common.tileentity.TileEntitySecurityStation$Listener onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		5: HIGH
		6: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		7: NORMAL
		8: ASM: class com.endertech.minecraft.forge.items.GlassMeter onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@4a5490df
		10: ASM: class io.github.wouink.furnish.event.KnockOnDoor onDoorHit(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		11: ASM: class com.dannyandson.tinyredstone.CommonBinding onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@6e24a0f1
		13: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@2eb12ef8
		14: ASM: class sonar.fluxnetworks.register.CommonEventHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		15: ASM: class gg.moonflower.pollen.core.forge.PollenCommonForgeEvents onEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		16: ASM: class me.desht.modularrouters.event.ClientEventHandler onPlayerLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		17: ASM: de.cheaterpaul.fallingleaves.init.EventHandler@50e357cc onAttackLeavesBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		18: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@5b2ae371 onPlayerLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		19: ASM: com.bobmowzie.mowziesmobs.server.ability.AbilityCommonEventHandler@14b917ff onPlayerLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		20: ASM: se.mickelus.tetra.effect.ItemEffectHandler@6e38faaf onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		21: ASM: class xfacthd.framedblocks.common.util.EventHandler onBlockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		22: ASM: class me.desht.pneumaticcraft.common.item.ItemGPSAreaTool$EventHandler onBlockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		23: ASM: class me.desht.pneumaticcraft.common.item.ItemMemoryStick$Listener onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		24: ASM: class me.desht.pneumaticcraft.common.item.ItemJackHammer$Listener onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		25: ASM: class com.github.alexthe666.rats.server.events.CommonEvents onPlayerLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		26: ASM: com.feywild.feywild.EventListener@cec8fa6 blockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		27: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@10458d6b
		28: ASM: class com.hollingsworth.arsnouveau.common.event.ReactiveEvents leftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		29: ASM: class com.hollingsworth.arsnouveau.common.block.TimerSpellTurret leftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		30: ASM: class com.minecraftabnormals.savageandravage.core.other.SREvents onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		31: ASM: stepsword.mahoutsukai.handlers.ServerHandler@31c898a7 leftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		32: ASM: stepsword.mahoutsukai.client.ClientHandler@4688a530 leftClickEventBlockP(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		33: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@7ef925d4
		34: ASM: class com.lilypuree.decorative_blocks.setup.ModSetup onLeftClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		35: ASM: class mod.chiselsandbits.events.LeftClickEventHandler onPlayerInteractLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		36: ASM: class com.simibubi.create.content.logistics.block.mechanicalArm.ArmInteractionPointHandler leftClickingBlocksDeselectsThem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		37: ASM: class com.simibubi.create.content.logistics.block.depot.EjectorTargetHandler leftClickingBlocksDeselectsThem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		38: ASM: class com.simibubi.create.content.curiosities.zapper.ZapperInteractionHandler leftClickingBlocksWithTheZapperSelectsTheBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		39: ASM: class com.ma.events.CommonEventHandler onBlockLeftClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		40: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@351131d2
		41: ASM: de.maxhenkel.camera.ServerEvents@4743b1a7 onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		42: ASM: de.teamlapen.vampirism.player.ModPlayerEventHandler@2a9d55fe onPlayerLeftLickedBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		43: ASM: com.lothrazar.cyclic.event.ItemEvents@55cd9bdb onHit(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		44: ASM: mcjty.lib.setup.ModSetup$EventHandler@6babc00e onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		45: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
		46: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@12f01f66
		47: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@2e62e686
		48: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@1982a11b
		49: ASM: me.desht.pneumaticcraft.common.event.UniversalSensorHandler@3fae40af onInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		50: ASM: com.mrcrayfish.vehicle.common.CommonEvents@77c7cf88 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		51: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@4caf7e6d onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		52: ASM: class cofh.ensorcellation.event.CommonEvents handlePlayerRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		53: ASM: appeng.parts.PartPlacement@46bf29b8 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		54: ASM: vazkii.quark.content.tweaks.module.ImprovedSleepingModule@2847727e onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		55: ASM: class team.creative.itemphysic.server.ItemPhysicServer onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		56: ASM: romelo333.notenoughwands.ForgeEventHandlers@3cda744e onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		57: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@7f9f40aa onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		58: ASM: class team.creative.itemphysic.client.ItemPhysicClient onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		59: ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@38a8dcec on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		60: ASM: mob_grinding_utils.events.ChickenFuseEvent@66260e86 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		61: LOW
		62: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@25a18c58
		63: LOWEST
		64: net.minecraftforge.eventbus.EventBus$$Lambda$3117/0x00000008019e5d20@3738aca5
		65: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem consumeDurabilityOnPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.util.Direction.func_82601_c()" because "☃" is null
	at net.minecraft.util.math.BlockPos.func_177972_a(SourceFile:214)
	at de.teamlapen.vampirism.player.ModPlayerEventHandler.onPlayerLeftLickedBlock(ModPlayerEventHandler.java:415)
	at net.minecraftforge.eventbus.ASMEventHandler_7900_ModPlayerEventHandler_onPlayerLeftLickedBlock_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:823)
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:130)
	at com.lothrazar.cyclic.base.TileEntityBase.leftClickBlock(TileEntityBase.java:148)
	at com.lothrazar.cyclic.block.user.TileUser.func_73660_a(TileUser.java:109)
	at net.minecraft.world.World.redirect$clk000$redirectTick(MixinWorldRedstone.java:4211)
	at net.minecraft.world.World.func_217391_K(MixinWorldRedstone.java:491)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Dunkmania101** [comment]
It looks like the issue isn't caused by this mod after all, or at least the change I reverted from wasn't the culprit.
I'll close this under the assumption that it's something else but I'm not entirely sure.

**Comment by Dunkmania101** [comment]
After staring at the error message for a while longer, I'm now pretty sure it's Vampirism.
I'll report it to them, sorry for any confusion.
